export interface User {
    id: number,
    email: string,
    password: string,
    firstName: string,
    lastName?: string,
    createdAt?: string,
    updatedAt?: string,
    role: number,
    avatar: string,
    posts?: [],
    status: boolean,
    birthAt: string,
    location: string,
}
